# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test Scouting App

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
        # Remove --force when cypress-ct-lit supports lit 3.0.0
      - run: npm ci --force
      - name: Cypress E2E tests
        uses: cypress-io/github-action@v6.6.1
        with:
          start: npm run dev
      - name: Cypress component tests
        uses: cypress-io/github-action@v6.6.1
        with:
          component: true
          start: npm run dev
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
